name: "Build Debian Live Nano ISO"

on:
  schedule:
  # 7AM on the 1st of every month (GitHub is GMT)
  # https://crontab.guru/#0_7_1_*_*
    - cron: "0 7 1 * *"

  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y%m')" >> $GITHUB_ENV

      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./build.sh

      - name: "Delete latest release."
        uses: cb80/delrel@latest
        continue-on-error: true
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Delete date-stamped tag if it already exists."
        uses: cb80/delrel@latest
        continue-on-error: true
        with:
          tag: "${{ env.DATESTAMP }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish Date-Time"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.DATESTAMP }}"
          title: "Debian Stable Live Nano ISO"
          files: |
            output/debian-stable-live-nano-x86_64-${{ env.DATESTAMP }}.iso
            output/packages.txt

      - name: "Rename the iso to use latest instead of a datetime"
        run: |
          mv output/debian-stable-live-nano-x86_64-${{ env.DATESTAMP }}.iso output/debian-stable-live-nano-x86_64-latest.iso

      - name: "Publish latest"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "LATEST: Debian Stable Live Nano ISO"
          files: |
            output/debian-stable-live-nano-x86_64-latest.iso
            output/packages.txt
